personal_care/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quizapp/', include('quizapp.urls')),
]

quizapp/urls.py
from django.urls import path, include
from quizapp import views
from quizapp import api
from rest_framework.routers import DefaultRouter


app_name = 'quizapp'

#router = DefaultRouter()
#router.register('customers',api.CustomerViewSet)

urlpatterns = [
    #api views
    path('', views.index, name='index'),
    path('customers/', api.CustomerList.as_view()),
    path('quiz1/', api.Quiz1.as_view()),
    path('skin_test/', api.SkinTestCreate.as_view()),
    #path('quiz_answers/', api.quiz_answers, name='quiz_answers'),
    path('quizanswers/', api.QuizAnswers.as_view()),

    path('dummy/', views.dummy, name='dummy'),
    path('skin_quiz/', views.skin_quiz, name='skin_quiz'),
    path('concerns_quiz/', views.concerns_quiz, name='concerns_quiz'),
    path('skin_concerns/<str:user_name>/<str:test_code>/', views.skin_concerns, name='skin_concerns'),
    path('products/<str:user_name>/<str:test_code>/', views.products, name='products'),
    path('test_info/<int:pk>/',views.test_info, name='test_info'),

    #api views
    #path('create_customer/', api.create_customer, name='create_customer'),
    

    path('questions_list/', api.questions_list, name='questions_list'),
    path('water_info/', api.water_info, name='water_info'),
    path('hydration_info/', api.HydrationInfo.as_view()),

    #path('api/',include(router.urls)),
    path('questions_test/', api.questions_test, name='questions_test'),
]

quizapp/models.py
import datetime
from django.db import models
from django.db.models import Q, F, Count, Sum
from django.utils import timezone
#from .result import oil_dry_anls
from django.core.exceptions import ObjectDoesNotExist


GENDER_CHOICES = [("1", "Male"), ("2", "Female"), ("3", "Others")]

AGE_CHOICES = (
    ("1", "18-25"),
    ("2", "26-35"),
    ("3", "36-45"),
    ("4", "46-55"),
    ("5", "55+"),
)


class PersonalCare(models.Model):
    code = models.CharField(null=True, blank=True, max_length=100)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Category(models.Model):
    personalcare = models.ForeignKey(PersonalCare, on_delete=models.CASCADE)
    code = models.CharField(null=True, blank=True, max_length=100)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Question(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    code = models.IntegerField(default=0)
    name = models.CharField(max_length=200)
    # pub_date = models.DateTimeField('date published')
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
    name = models.CharField(max_length=200)
    marks = models.FloatField()

    def __str__(self):
        return self.name

class Customer(models.Model):
    employee_id = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='1')
    age = models.CharField(max_length=1, choices=AGE_CHOICES, default='1')
    location = models.CharField(max_length=100)

    def __str__(self):
        # return self.name
        return f'{self.employee_id} - {self.name}'
    
    @property
    def get_oil_dry(self):
        '''it's return get_oil_dry'''
        oil_dry_ctx = None #oil_dry_anls(self.employee_id)
        return oil_dry_ctx
    
    @property
    def get_hydration(self):
        '''it's return get_oil_dry'''
        try:
            hydration = Hydration.objects.get(self.employee_id)
        except ObjectDoesNotExist:
            hydration = None
        return hydration


class SkinTest(models.Model):
    code = models.IntegerField(default=0, unique=True)
    pub_date = models.DateTimeField(auto_now_add=True, editable=False)
    customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.SET_NULL)
    #customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.SET_NULL, related_name='skintests_customer')
    #customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.SET_NULL, related_name="skintests",)

    def __str__(self):
        #return self.code
        return str(self.code)
        

    def save(self, *args, **kwargs):
        if not self.code:
            try:
                top = SkinTest.objects.order_by('-code')[0]
                self.code = top.code + 1
            except IndexError:
                self.code = 1
        super(SkinTest, self).save(*args, **kwargs)


class QuizModal(models.Model):
    skin_test = models.ForeignKey(SkinTest, on_delete=models.CASCADE, null=True, blank=True)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True, editable=False)
    customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.SET_NULL)
    result = models.FloatField(default=0)

    def __str__(self):
        return str(self.choice)


class Hydration(models.Model):
    skin_test = models.ForeignKey(SkinTest, on_delete=models.CASCADE, null=True, blank=True)
    customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.SET_NULL)
    weight = models.FloatField(default=0)
    physical_activity = models.FloatField(default=0)
    water_intake = models.FloatField(default=0)
    status = models.CharField(max_length=200)


class Concerns(models.Model):
    skin_test = models.ForeignKey(SkinTest, on_delete=models.CASCADE, null=True, blank=True)
    customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ManyToManyField(Category, related_name='concerns')
    is_primary = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='is_primary')


class Products(models.Model):
    code = models.IntegerField(default=0)
    title = models.CharField(max_length=100)
    cleanser = models.CharField(max_length=100)
    moisturizer = models.CharField(max_length=100)
    serum = models.CharField(max_length=100)

    def __str__(self):
        return self.title

class Skin_profile(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    from_score = models.FloatField(default=0)
    to_score = models.FloatField(default=0)
    skin_status = models.CharField(max_length=200)

    def __str__(self):
        return self.skin_status

quizapp/forms.py
import re
from django import forms
from django.core.validators import validate_email
from .models import *


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

quizapp/views.py
import json
from django.db.models import Case, When, IntegerField
from django.template.loader import render_to_string, get_template
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from .models import Choice, Question, PersonalCare, Category, QuizModal, Customer, Hydration, Concerns, Products, Skin_profile, SkinTest
from .forms import CustomerForm
from django.db.models import Q, F, Count, Sum, Avg
from .result import *
from .score import oil_dry_anls, sen_res_anls, acne_anls, pigmentation_anls, ageing_anls, product_info

def index(request):
    context = {
        'form': CustomerForm()
    }    
    return render(request, 'quizapp/index.html', context)


def dummy(request):
    return render(request, 'quizapp/dummy.html')

def skin_quiz(request):
    return render(request, 'quizapp/skin_quiz.html')


def skin_concerns(request, user_name, test_code):
    pc_data = get_object_or_404(PersonalCare, id=2)
    oil_dry_ctx = oil_dry_anls(test_code)
    skin_type = oil_dry_ctx['oil_dry_analysis']

    if skin_type in ['Combination Skin (Slightly Oily)', 'Oily Skin']:
        category = Category.objects.filter(Q(personalcare_id=pc_data.id) & ~Q(code=104))
    elif skin_type in ['Dry Skin', 'Normal Skin']:
        category = Category.objects.filter(Q(personalcare_id=pc_data.id) & ~Q(code=105))
    else:
        category = Category.objects.filter(personalcare_id=pc_data.id)
        
    
    context = {
        'category': category,
        'pc_data': pc_data,
        'oil_dry_ctx' : oil_dry_ctx
    }
    return render(request, 'quizapp/skin_concerns.html', context)


def concerns_quiz(request):
    primary = request.GET.get('primary')
    category_choice = request.GET.getlist('checkbox')
    user_name = request.GET.get('user_name')
    test_code = request.GET.get('test_code')
    specific_concerns = [104, 105, 106]

    customer_obj = Customer.objects.get(employee_id=user_name)
    skin_test_obj = SkinTest.objects.get(code=test_code)

    if category_choice and primary:
        category_data  = Category.objects.filter(pk__in=category_choice)
        concerns_save = Concerns()
        concerns_save.customer = customer_obj
        concerns_save.is_primary = Category.objects.get(pk=primary)
        concerns_save.skin_test = skin_test_obj
        concerns_save.save()
        for x in category_data:
            concerns_save.category.add(x)
        
        questions_data = Question.objects.filter(Q(category_id__in=category_choice) & ~Q(category__code__in=specific_concerns))
        if customer_obj.get_gender_display() == 'Male':
            questions_data = questions_data.filter(~Q(code=119)) #specific_concerns.append(119)

        if questions_data.exists():
            questions = questions_data.annotate(concern_sort=Case(When(category_id=primary, then=1), default=0, output_field=IntegerField()))
            questions.order_by('-concern_sort')
        else:
            return redirect('quizapp:products', user_name=customer_obj.employee_id, test_code=test_code)

    context = {
        'questions': questions,
        'quiz_type': 'concerns'
    }
    return render(request, 'quizapp/skin_quiz.html', context)


def products(request, user_name, test_code):            
    oil_dry_ctx = oil_dry_anls(test_code)
    sen_res_ctx = sen_res_anls(test_code)
    acne_anls_ctx = acne_anls(test_code)
    pigmentation_anls_ctx = pigmentation_anls(test_code)
    ageing_anls_ctx = ageing_anls(test_code)
    concern_obj = Concerns.objects.get(skin_test__code=test_code)
    product_data = product_info(test_code, concern_obj, oil_dry_ctx, sen_res_ctx, acne_anls_ctx)
    test_data = SkinTest.objects.filter(customer__employee_id=user_name)

    context = {
        'oil_dry_ctx' : oil_dry_ctx,
        'sen_res_ctx' : sen_res_ctx,
        'acne_anls_ctx' : acne_anls_ctx,
        'pigmentation_anls_ctx' : pigmentation_anls_ctx,
        'ageing_anls_ctx' : ageing_anls_ctx,
        'concerns' : concern_obj,
        'pro_obj' : product_data,
        'test_data' : test_data,
        'user_name' : user_name
    }
    return render(request, 'quizapp/products.html', context)


def test_info(request, pk):
    skin_test_obj = SkinTest.objects.get(pk=pk)
    print(skin_test_obj.id)
    oil_dry_ctx = oil_dry_anls(skin_test_obj.code)
    sen_res_ctx = sen_res_anls(skin_test_obj.code)
    acne_anls_ctx = acne_anls(skin_test_obj.code)
    pigmentation_anls_ctx = pigmentation_anls(skin_test_obj.code)
    ageing_anls_ctx = ageing_anls(skin_test_obj.code)
    concern_obj = Concerns.objects.get(skin_test=skin_test_obj.pk)
    product_data = product_info(skin_test_obj.code, concern_obj, oil_dry_ctx, sen_res_ctx, acne_anls_ctx)

    context = {
        'oil_dry_ctx' : oil_dry_ctx,
        'sen_res_ctx' : sen_res_ctx,
        'acne_anls_ctx' : acne_anls_ctx,
        'pigmentation_anls_ctx' : pigmentation_anls_ctx,
        'ageing_anls_ctx' : ageing_anls_ctx,
        'concerns' : concern_obj,
        'pro_obj' : product_data,
        'test_data' : skin_test_obj
    }
    return render(request, 'quizapp/test_info.html', context)

templates/quizapp/dummy.html
<div id="data">
    <table class="table">
        <thead class="thead-dark">
            <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
            </tr>
        </thead>
        <tbody>
            <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>@mdo</td>
            </tr>
            <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
            </tr>
            <tr>
            <th scope="row">3</th>
            <td>Larry</td>
            <td>the Bird</td>
            <td>@twitter</td>
            </tr>
        </tbody>
    </table>
</div>

templates/quizapp/index.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load static %}

{% block content %}
<style>
    /* https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_background_hero */
    html, body  { 
        background: url("/static/images/127.jpg") no-repeat center center fixed; 
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }
</style>
    <h1 class="display-1 mt-3 text-center">Personal Care</h1>
     <div>
        <h2 class="display-4 text-center">Skin Analysis</h2>
        <p></p>
        <div class="text-center"> 
           <a class="btn orb-btn show-form" data-url="/quizapp/customers/"
            data-toggle="modal" data-target="#modal-quiz">Take Quiz&nbsp;&raquo;
            </a> 
        </div> 
    </div>

    <div id="loader"></div>    
    <div class="modal fade" id="modal-quiz">
        <div class="modal-dialog">
            <div class="modal-content" id="modal-content">
                <form method="POST" data-url="/quizapp/customers/" class="create-form" id="form">
                    {% csrf_token %}
                    <div class="modal-header">
                        <h5 class="modal-title">Create Profile</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">
                        <div class="mb-6">
                            {{ form|crispy }}
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary save-form">Process</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

<div hidden>
    <div class="card mt-4 shadow-sm border-info" style="width: 50rem;">
        <div class="card-header border-info">
            <h4 class="my-0 font-weight-normal">Welcome!
                <span class="name"></span>
                <span id="ques_count" style="margin-left: 15%;"></span>
            </h4>
        </div>
        <div class="card-body border-info quiz_body">
            <div id="questions">
                <h3 id="question"></h3>
                <form name="watr-intake" id="watr-intake" class="option_group">
                    <table class="option_table"><tbody id="option_table"></tbody></table>
                    <h3 class="float-right pt-3" id="water-content"></h3>
                </form> 
                <p id="note" class="pt-5 d-none"></p>
            </div>
        </div>
        <div class="card-footer text-muted border-info">
            <a id="btn-previous" class="btn btn-primary orb-btn invisible" href="#" onclick="previous()">Previous</a>
            <a id="btn-next" class="btn btn-primary orb-btn float-right invisible" href="#" onclick="next()">Next Question</a>
        </div>
    </div>
</div>

{% endblock %}

{% block extraJS %}

<script src="{% static 'js/index.js' %}"></script>

{% endblock %}

templates/quizapp/products.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load static %}
{% block content %}
<style>
    .table td.fit, 
    .table th.fit {
        white-space: nowrap;
        width: 1%;
    }
    .container {
        margin-left:10%;
    }
    .auto-index {
        counter-reset: serial-number;
    }

    .auto-index td:first-child:before {
        counter-increment: serial-number;
        content: counter(serial-number);
    }
    .table td:first-child {
        text-align: right;
    }
   
</style>
<div class="card mt-4 shadow-sm border-info card-size">
    <div class="card-header border-info">
        <h5 class="my-0 font-weight-normal">Skin Analysis Report</h5>
    </div>
    <div class="card-body border-info">
        <table class="table table-bordered auto-index">
        <thead class="table-primary">
        <tr>
            <th class="fit">S.No</th>
            <th>Category Name</th>
            <th>Status</th>
            <th>Marks</th>
        </tr>
        </thead>
        <tbody>
        {% if oil_dry_ctx %}
        <tr>
            <td class="fit"></td>
            <td>Strip Analysis</td>
            <td>{{ oil_dry_ctx.strip_analysis }}</td>
            <td class="text-center">{{ oil_dry_ctx.strip_score }}</td>
        </tr>
        <tr>
            <td class="fit"></td>
            <td>Oil Dry Quiz Score</td>
            <td>{{ oil_dry_ctx.quiz_analysis }}</td>
            <td class="text-center">{{ oil_dry_ctx.quiz_score }}</td>
        </tr>
         <tr>
            <td class="fit"></td>
            <td colspan="3" class="font-weight-bold">
                Oil Dry Final analysis (Strip+Quiz) <span class="font-weight-normal">&nbsp;&nbsp; = {{ oil_dry_ctx.oil_dry_analysis }}</span>
            </td>
        </tr>
        <tr>
            <td class="fit"></td>
            <td colspan="3" class="font-weight-bold">
                Hydration and pH <span class="font-weight-normal">&nbsp;&nbsp; = {{ oil_dry_ctx.hydration }}</span>
            </td>
        </tr>
        {% endif %}
        <tr>
            <td class="fit"></td>
            <td>Sen-Res Score</td>
            <td>{{ sen_res_ctx.sen_res_analysis }}</td>
            <td class="text-center">{{ sen_res_ctx.sen_res_score }}</td>
        </tr>
        
        {% if concerns %}
        <tr>
            <td class="fit"></td>
            <td>Concerns</td>
            <td>Concerns: {{ concerns.category.all|join:", " }}</td>
            <td class="text-center">Primary: {{ concerns.is_primary }}</td>
        </tr>
        {% endif %}
        
        {% if acne_anls_ctx.acne_analysis %}
        <tr>
            <td class="fit"></td>
            <td>Acne Score</td>
            <td>{{ acne_anls_ctx.acne_analysis }}</td>
            <td class="text-center">{{ acne_anls_ctx.acne_score }}</td>
        </tr>
        {% endif %}
        {% if pigmentation_anls_ctx.pigmentation_analysis %}
        <tr>
            <td class="fit"></td>
            <td>Pigmentation Score</td>
            <td>{{ pigmentation_anls_ctx.pigmentation_analysis }}</td>
            <td class="text-center">{{ pigmentation_anls_ctx.pigmentation_score }}</td>
        </tr>
        {% endif %}
        {% if wrinkletight_anls_ctx.wrinkletight_analysis %}
        <tr>
            <td class="fit"></td>
            <td>Wrinkletight Score</td>
            <td>{{ wrinkletight_anls_ctx.wrinkletight_analysis }}</td>
            <td class="text-center">{{ wrinkletight_anls_ctx.wrinkletight_score }}</td>
        </tr>
        {% endif %}
        {% if pro_obj %}
        <tr>
            <td class="fit"></td>
            <td>Recommended Products</td>
            <td class="" colspan="2">({{ pro_obj.code }})&nbsp;{{ pro_obj.cleanser }}, {{ pro_obj.moisturizer }}, {{ pro_obj.serum }}</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    </div>
</div>
{% endblock %}

templates/quizapp/quiz_test.html
<div class="card mt-4 shadow-sm border-info" style="width: 50rem;">
        <div class="card-header border-info">
            <h4 class="my-0 font-weight-normal">Welcome!
                <span class="name"></span>
                <span id="ques_count" style="margin-left: 15%;"></span>
            </h4>
        </div>
        <div class="card-body border-info quiz_body">
            <div id="questions">
                <h3 id="question"></h3>
                <form name="watr-intake" id="watr-intake" class="option_group">
                    <table class="option_table"><tbody id="option_table"></tbody></table>
                    <h3 class="float-right pt-3" id="water-content"></h3>
                </form> 
                <p id="note" class="pt-5 d-none"></p>
            </div>
        </div>
        <div class="card-footer text-muted border-info">
            <a id="btn-previous" class="btn btn-primary orb-btn invisible" href="#" onclick="previous()">Previous</a>
            <a id="btn-next" class="btn btn-primary orb-btn float-right invisible" href="#" onclick="next()">Next Question</a>
        </div>
    </div>

templates/quizapp/skin_concerns.html
{% extends 'base.html' %}{% load static %}
{% block content %}
    <style>
        .big-checkbox {
            width: 30px;
            height: 25px;
        }

        .modal-body {
            background-color: #C0C0C0;
        }

        .card-size {
            min-width: 18rem;
        }

        .modal-card-size {
            min-width: 8rem;
        }
    </style>

    <div class="card mt-4 shadow-sm border-info card-size">
        <div class="card-body border-info">
            <div class="pricing-header px-3 py-3 pt-md-3 pb-md-0 mx-auto text-center">
                <h1 class="display-4">{{ pc_data.name }}</h1>
                <p class="lead">
                    Please Select your skin concerns (Min: 1 & Max: 3)
                </p>
            </div>
            <hr class="border-info mb-0">
            <div class="card-deck mb-4 text-center">
            {% for x in category %}
                <div class="card mt-4 shadow-sm border-info card-size" id="cat-card">
                    <div class="card-header border-info">
                        <h5 class="my-0 font-weight-normal">{{ x.name }}</h5>
                    </div>
                    <div class="card-body border-info">
                        <p>information</p>
                    </div>
                    <div class="card-footer text-muted border-info">
                        <input type="checkbox" value="{{ x.id }}" class="big-checkbox primary-checkbox" name="primary" data-name="{{ x.name }}">
                        <input type="checkbox" value="{{ x.id }}" class="concerns-checkbox" name="checkbox" hidden>
                    </div>
                </div>
            {% endfor %}
        </div>
        <a class="btn btn-outline-info" href="{% url 'quizapp:index' %}">Back</a>
        <a class="btn orb-btn float-right invisible concerns" id="concernsBtn">Concerns&raquo;</a>
    </div>

    {{ oil_dry_ctx.oil_dry_analysis }}
    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" id="modal-quiz"
         aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <form method="get" action="{% url 'quizapp:concerns_quiz' %}" name="concern_form" class="concern-form">
                <input name="user_name" type="text" hidden>
                <input name="test_code" type="text" hidden>
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Please select skin concern you would like to address first.</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="card-deck mb-4 text-center" id="card-load"></div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Process</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {{ test_code }}
    {% endblock %}
    
    {% block extraJS %}
    
    <script type="application/javascript">
        let user_name = sessionStorage.getItem("user_name");
        let test_code = sessionStorage.getItem("test_code");
        document.concern_form.user_name.value = user_name;
        document.concern_form.test_code.value = test_code;
        let skin_type = "{{ oil_dry_ctx.oil_dry_analysis }}";

        let checkbox = document.querySelector('.card-deck');
        let s = new Set();
        //https://stackoverflow.com/questions/37073774/using-lodash-push-to-an-array-only-if-value-doesnt-exist
        checkbox.onchange = (e) => {
            let elm = e.target;
            let elm_name = elm.dataset.name;
            let concernsBtn = document.getElementById('concernsBtn');

            if(e.target.checked){                
                s.add(elm.value)
                
                if (s.has(String(5)) && s.has(String(10))) {
                    s.delete(elm.value);
                    elm.checked = false;
                    alert('skin concerns error: both oily and dry skin is not possible');
                } else if (s.size > 3) {
                    s.delete(elm.value);
                    elm.checked = false;
                    alert('you can select min: 1 and max: 3');
                } else if (s.size >= 1) {
                    concernsBtn.classList.remove('invisible');
                }
            } else {
                s.delete(elm.value);
            }
            //values = Array.from(s);
        }
        
        
        $(document).ready(function () {
            $(".concerns").click(function () {
                //https://jsfiddle.net/4bnx8acw/15/
                //let elm_test = document.querySelectorAll('input[type="checkbox"]:checked').copy
                let option_elm = document.querySelectorAll('input[type="checkbox"]:checked');
                let elm_clone = $(option_elm).parent().closest("#cat-card");
                $("#modal-quiz").modal('show');
                $("#card-load").html(elm_clone.clone());
                $("#card-load .card").removeClass('card-size').addClass('modal-card-size');
                $('#card-load .primary-checkbox').attr('type', 'radio');
                $('#card-load .concerns-checkbox').prop('checked', true);
            });

            $('#modal-quiz').on('hidden.bs.modal', function () {
                $("#card-load").empty();
            });

            /*
            var SaveForm = function (e) {
                e.preventDefault();
                var form = $(this);
                console.log(form.attr('data-url'))
                $.ajax({
                    url: form.attr('data-url'),
                    data: form.serialize(),
                    type: form.attr('method'),
                    dataType: 'json',
                    success: function (data) {
                        console.log(data)
                    }
                })
            };

            // create
            //$(".show-form").click(ShowForm);
            $("#modal-quiz").on("submit", ".concern-form", SaveForm);
            */

        });

    </script>
    {% endblock %}

templates/quizapp/skin_quiz.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load static %}
{% block content %}
    <div class="card mt-4 shadow-sm border-info" style="width: 50rem;">
        <div class="card-header border-info">
            <h4 class="my-0 font-weight-normal">Welcome!
                <span class="name"></span>
                <span id="ques_count" style="margin-left: 15%;"></span>
            </h4>
        </div>
        <div class="card-body border-info quiz_body">
            <div id="questions">
                <h3 id="question"></h3>
                <form name="watr-intake" id="watr-intake" class="option_group">
                    <table class="option_table"><tbody id="option_table"></tbody></table>
                    <h3 class="float-right pt-3" id="water-content"></h3>
                </form> 
                <p id="note" class="pt-5 d-none"></p>
            </div>
        </div>
        <div class="card-footer text-muted border-info">
            <a id="btn-previous" class="btn btn-primary orb-btn invisible" href="#" onclick="previous()">Previous</a>
            <a id="btn-next" class="btn btn-primary orb-btn float-right invisible" href="#" onclick="next()">Next Question</a>
        </div>
    </div>

{% endblock %}
{% block extraJS %} <script src="{% static 'js/quiz.js' %}"></script> {% endblock %}